# Generated by Django 3.2.4 on 2021-06-16 08:05

from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('city', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('linkedin_profile', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('content', froala_editor.fields.FroalaField()),
                ('created_on', models.DateField()),
                ('updated_on', models.DateField()),
                ('image', models.ImageField(upload_to='')),
                ('tags', models.CharField(max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
